nodeDownloadMirrors:
  release: https://npmmirror.com/mirrors/node/

minimumReleaseAgeExclude:
  - dayjs@1.11.22 || 1.11.23
  - eslint-plugin-tailwindcss@4.3.0
shellEmulator: true
trustPolicy: no-downgrade
trustPolicyExclude:
  - semver@6.3.1

packages: []

allowBuilds:
  vue-demi: true

overrides:
  '@trickfilm400/rollup-plugin-off-main-thread': 4.0.0-pre2
